 nome: Empregos para atualizar dados
 em funcionamento: ubuntu-mais recente
 passos:
      # Cartões de resumo
 - usos: ações/checkout@v2
 - usos: vn7n24fzkq/github-profile-summary-cards@release
        env:
 GITHUB_TOKEN: ${{ segredos. GITHUB_TOKEN }}
 com:
 NOME DE USUÁRIO: ${{ github.repository_owner }}

      # Animação cobra
 - usos: Platane/snk@master
        id: snake-gif
